name: Run build.sh

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Ermöglicht manuelles Auslösen

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make build.sh executable
        run: chmod +x ./build.sh

      - name: Run build.sh
        run: ./build.sh
