name: Run build.sh daily at 13:00

on:
  schedule:
    - cron: '0 13 * * *'  # Jeden Tag um 13:00 Uhr UTC
  workflow_dispatch:  # Ermöglicht manuelles Auslösen

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make build.sh executable
        run: chmod +x ./build.sh

      - name: Run build.sh
        run: ./build.sh
